# Generated by Django 2.1.5 on 2019-01-07 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import erphts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('erphts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id_canton', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_canton', models.CharField(max_length=100, unique=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id_parish', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_parish', models.CharField(max_length=100, unique=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('canton', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parish_c', to='erphts_app.Canton')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('identification_card', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=75)),
                ('active', models.BooleanField(default=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('parish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parish_person', to='erphts_app.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=75)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_register_pf', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_pf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_login', models.DateTimeField(blank=True, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profusr_Profile', to='erphts_app.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profusr_user', to=settings.AUTH_USER_MODEL)),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_register_pu', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_pu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description_province', models.CharField(max_length=100, unique=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='users',
            field=models.ManyToManyField(through='erphts_app.ProfileUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canton',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantones_p', to='erphts_app.Province'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='erphts_app.Person'),
        ),
    ]
