# Generated by Django 2.1.5 on 2019-01-08 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import erphts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('erphts_app', '0002_auto_20190107_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialLine',
            fields=[
                ('id_com_line', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id_enterprise', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ruc', models.CharField(max_length=13, null=True)),
                ('name', models.CharField(max_length=100)),
                ('legal_agent', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=10, null=True)),
                ('telephone_fax', models.CharField(max_length=10, null=True)),
                ('movil_phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=70, null=True)),
                ('neighborhood', models.CharField(max_length=70, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('web_site', models.CharField(max_length=200, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('central_ent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='erphts_app.Enterprise')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_comp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContributor',
            fields=[
                ('id_type_contributor', models.UUIDField(default=erphts_app.models.make_id_model, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
