# Generated by Django 2.1.5 on 2019-01-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erphts_app', '0003_activity_commercialline_enterprise_typecontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_acty', to='erphts_app.Activity'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='comm_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_commline', to='erphts_app.CommercialLine'),
        ),
    ]
