# Generated by Django 2.1.5 on 2019-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erphts_app', '0005_auto_20190108_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commercialline',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typecontributor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
