# Generated by Django 2.1.5 on 2019-01-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erphts_app', '0006_auto_20190108_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='type_contrib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_typeCon', to='erphts_app.TypeContributor'),
        ),
    ]
